# Generated by Django 3.1 on 2020-08-24 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='phone_test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=30, verbose_name='手机号')),
                ('country', models.CharField(max_length=30, verbose_name='国家(默认为+86)')),
                ('information_url', models.CharField(max_length=1000, verbose_name='跳转到短信url')),
                ('source', models.CharField(max_length=100, verbose_name='来源网站')),
                ('Creation_time', models.CharField(max_length=30, verbose_name='创建时间')),
            ],
        ),
    ]
