# Generated by Django 3.1.1 on 2020-10-15 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone_backstage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='gps_position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_models', models.CharField(max_length=1000, verbose_name='手机型号')),
                ('title', models.CharField(max_length=1000, verbose_name='标题')),
                ('content', models.CharField(max_length=1000, verbose_name='内容')),
                ('longitude', models.CharField(max_length=1000, verbose_name='经度')),
                ('latitude', models.CharField(max_length=1000, verbose_name='纬度')),
                ('detailed_address', models.CharField(max_length=1000, verbose_name='详细地址')),
                ('creation_time', models.CharField(max_length=1000, verbose_name='创建时间')),
            ],
        ),
    ]
